stocks:
  outputs:
    dev:
      type: duckdb
      schema: main
      path: md:stocks_dev
      threads: 1
      extensions:
        - httpfs
    local:
      type: duckdb
      schema: main
      path: stocks_local.db
    ducklakemd:
      type: duckdb
      attach:
        - path: "md:stocks_ducklake"
          is_ducklake: true
          alias: my_catalog
      threads: 1
      extensions:
        - httpfs
  target: ducklakemd

